backend:
  name: github
  repo: munizcesar/InSpotGO-US
  branch: main

media_folder: public/imagespost
public_folder: /imagespost

collections:
  - name: posts
    label: Posts
    folder: src/content/posts
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Date, name: date, widget: datetime}
      - {label: Category, name: category, widget: select, options: ["Tech", "SaaS", "Software", "Guides"]}
      - {label: Tags, name: tags, widget: list}
      - {label: Description, name: description, widget: text}
      - {label: Cover, name: cover, widget: image}
      - {label: Body, name: body, widget: markdown}
